USERNAME_ALREADY_EXISTS = "Username already exists"
EMAIL_ALREADY_EXISTS = "Email already exists"
NO_USER_FOUND_BY_USERNAME = "No user found by username: "
FOUND_USER_BY_USERNAME = "Returning found user by username: "
NO_USER_FOUND_BY_EMAIL = "No user found for email: "