package org.event.Entity;

public enum EventCategory {

        DIRECT_ACCESS_TO_THE_BEACH,
        HEATED_SWIMMING_POOL,
        INDOOR_SWIMMING_POOL,
        BALNEAOTHERAPY_HAMMAM_SAUNA,
        EQUIPPED_WITH_CHILDRENS_MIN_CLUBS,
        EQUIPPED_WITH_WATER_PARKS,
        WITH_UNUSUAL_ACCOMMODATION,
        LIVELIEST_CAMPING,
        AROUND_LAKES_AND_RIVERS,
        SPORTY,
        ECO_FRIENDLY_CAMPING,
        OFFERING_LUXURY_RENTALS,
        CAMPING_OPEN_YEAR_ROUND,
        YOUR_SECOND_HOME_ON_THE_CAMPING


}


